[build]
    cmd = "go build -o /app/bin/app ./cmd/snowman/main.go"
    bin = "./bin/app"
    dir = "."
    include_ext = ["go"]
    exclude_dir = ["vendor", "tmp"]
    run_after_build = "chmod +x ./bin/app"
    poll = true
